a = int(input('Digit the first number: '))
b = int(input('Digit the secondo number: '))
print('The sum is: {}'.format(a+b))
print('The subtraction is: {}'.format(a-b))
print('The division is: {:.3f}'.format(a/b))
print('The multiplication is: {}'.format(a*b))
print('The power is: {}'.format(a**b))
print('The real division is: {}'.format(a//b))
print('The module is: {}'.format(a%b))
