variable = input('Digit a variable: ')
print('The primitive type of this variable is:', type(variable))
print('Is it a space?', variable.isspace())
print('Is it a number?', variable.isnumeric())
print('Is it a letter?', variable.isalpha())
print('Is it a alphanumeric?', variable.isalnum())
print('Is it in uppercase?', variable.isupper())
print('Is it in lowercase?', variable.islower())
print('Is it capitalized? ', variable.istitle())
