a = int(input("Digit a number to see his multiplication table: "))
print(f"The number {a} multiplied by 1 is: {a*1}")
print(f"The number {a} multiplied by 2 is: {a*2}")
print(f"The number {a} multiplied by 3 is: {a*3}")
print(f"The number {a} multiplied by 4 is: {a*4}")
print(f"The number {a} multiplied by 5 is: {a*5}")
print(f"The number {a} multiplied by 6 is: {a*6}")
print(f"The number {a} multiplied by 7 is: {a*7}")
print(f"The number {a} multiplied by 8 is: {a*8}")
print(f"The number {a} multiplied by 9 is: {a*9}")
print(f"The number {a} multiplied by 10 is: {a*10}")